### PR TITLE
feat: add [squash_merge|merge]_commit_[messsage|title]

### PR DESCRIPTION
**Pull request by kevcube**
adds parameters for configuring default commit titles and messages for squash merges and merge commits

### CODE REVIEW

**Comment by soerenmartius** [comment]
Thanks for providing this - we will review this asap and make sure to update all github modules to the latest provider version asap too

**Comment by VOVELEE** [comment]
@soerenmartius @kevcube thanks for this PR. 
I also need this functionality :)

**Comment by soerenmartius** [comment]
> @soerenmartius @kevcube thanks for this PR. I also need this functionality :)

We have a major round of refactoring coming in :) this will be released soon

**Comment by hibeekaey** [comment]
Hey @soerenmartius, Could you share any updates on when we might expect this release? Any insights would be greatly appreciated.

**Pull request closed without merging**
